package com.springboot.laptop.model.dto.response;

public enum ErrorCode {
    DELETE_PRODUCT_ERROR, FIND_PRODUCT_ERROR,EXIST_USER, FIND_CATEGORY_ERROR, DELETE_CATEGORY_ERROR, ADD_CATEGORY_ERROR, DUPLICATED_DATA, ADD_BRAND_ERROR, NOT_FOUND_EXCEPTION, DATA_INTEGRITY_VIOLATION_ERROR, INTERNAL_SERVER_ERROR, FAIL_AUTHENTICATION
}
